backend:
  name: github
  repo: jiwonac/jiwonac.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: Ov23liQVyzbEUfFSRC8t

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false}
      - {label: "Tags", name: "tags", widget: "hidden", default: "blog"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Alt Text", name: "alt", widget: "string", required: false}
      - {label: "Blurb", name: "blurb", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "microblog"
    label: "Microblog"
    folder: "src/microblog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false}
      - {label: "Tags", name: "tags", widget: "hidden", default: "microblog"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Alt Text", name: "alt", widget: "string", required: false}
      - {label: "Blurb", name: "blurb", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "research"
    label: "Research"
    folder: "src/research"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Collaborators", name: "collaborators", widget: "list", required: false}
      - {label: "Date", name: "date", widget: "datetime", time_format: false}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["research"]}
      - {label: "Blurb", name: "blurb", widget: "text", required: false}
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Icon Image", name: "image", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "writings"
    label: "Writings"
    folder: "src/writings"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Alt Text", name: "alt", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["writings"]}
      - {label: "External URL", name: "url", widget: "string", required: false, hint: "Link to external publication"}
      - {label: "Permalink", name: "permalink", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
